# Generated by Django 4.0.3 on 2022-05-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belleza_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourName', models.TextField(blank=True)),
                ('YourEmail', models.TextField(blank=True)),
                ('YourAddress', models.TextField(blank=True)),
                ('YourConcern', models.TextField(blank=True)),
                ('YourMessage', models.TextField(blank=True)),
            ],
        ),
    ]
