# Generated by Django 4.0.3 on 2022-07-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellezasys', '0005_remove_order_state_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
