# Generated by Django 4.0.3 on 2022-07-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellezasys', '0006_remove_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
