# Generated by Django 4.0.3 on 2022-07-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellezasys', '0008_rename_email_customer_address_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
