# Generated by Django 4.0.3 on 2022-07-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellezasys', '0009_remove_order_customer_alter_review_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
